[REF] Change the linked examples to recipe repo
neurobagel/documentation pull request #158
Opened 2024-01-29 18:28 UTC by surchs

- Closes #144 

## Checklist

- [ ] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`) _(see https://neurobagel.org/contributing/pull_requests for more info)_
- [ ] PR links to GitHub issue with mention `Closes #XXXX`
- [ ] Checks pass

2024-02-02 09:17 UTC, alyssadai requested changes
Hey @surchs, sorry for the delay with this review!

The changes are looking good, but I noticed there are still a few remaining sections on this docs page that refer to files from the neurobagel/api repo (I did a quick search for "api repo" to double check), which should also be updated as part of this PR.

Since I can't seem to comment directly on lines that weren't changed, I've summarized these in my last comment below!

2024-02-02 09:17 UTC, alyssadai commented on docs/infrastructure.md
It looks like there are a few sections in this page where files from the `neurobagel/api` repo is still referred to for setup, and need to be updated to use corresponding files from `neurobagel/recipes` instead:
- "Uploading data to the graph"
- "Adding vocabulary files to the graph database"
  - Related to an open issue https://github.com/neurobagel/recipes/issues/14
- "Updating your Neurobagel API configuration"
  > For example, the [.template-env](https://github.com/neurobagel/api/blob/main/.template-env) file in the Neurobagel API repo...

In the "Docker Compose" section, I would also update
> Run the following in the repository root (where the `docker-compose.yml` file is)

to

> Run the following in the directory containing both the `docker-compose.yml` file from the [`local_nodes` recipe](link) and the `.env` file you just created.

2024-02-02 20:22 UTC, surchs commented
See also:
- https://github.com/neurobagel/api/pull/272
- https://github.com/neurobagel/api/pull/272

2024-02-03 04:48 UTC, alyssadai approved these changes
Thanks for the changes @surchs! Some final corrections below with regards to repo naming, and I think we're gtg 🧑‍🍳

2024-02-03 04:48 UTC, alyssadai commented on docs/infrastructure.md
>  For detailed instructions regarding the query tool see [Running cohort queries](query_tool.md).
```suggestion
(Detailed instructions for using the query tool can be found in [Running cohort queries](query_tool.md).)
```

2024-02-03 04:48 UTC, alyssadai commented on docs/infrastructure.md
> +For example, the [`template.env`](https://github.com/neurobagel/recipes/blob/main/local_node/template.env) file in the Neurobagel API repo assumes you want to allow API requests from a query tool hos
````suggestion
For example, add the following line to your `.env` file to allow API requests from a query tool hosted at a specific port on `localhost` (see the [Docker Compose section](#docker-compose)).

```bash
NB_API_ALLOWED_ORIGINS="http://localhost:3000 http://127.0.0.1:3000"
```
````

2024-02-03 04:48 UTC, alyssadai commented on docs/infrastructure.md
>  If you have cloned the api repository, you will already have downloaded the vocabulary file.
```suggestion
If you have cloned this repository, you will already have downloaded the vocabulary file.
```

2024-02-03 17:03 UTC, surchs commented on docs/infrastructure.md
>  Run the following code (assumes you are in the `api` directory):
Thanks for finding these! I thought I had caught them all.

2024-02-03 17:05 UTC, surchs commented
The dead links check failing is expected, because these links are anticipating that https://github.com/neurobagel/recipes/pull/15 will be merged as is.

2024-02-03 17:06 UTC, merged